apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres-deployment
  namespace: url-shortener
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
        - name: postgres
          image: postgres:16

          envFrom:
            - secretRef:
                name: postgres-secret

          ports:
            - containerPort: 5432

          volumeMounts:
            - mountPath: /var/lib/postgresql/data
              name: url-shortener-data

      volumes:
        - name: url-shortener-data
          persistentVolumeClaim:
            claimName: postgres-pvc