apiVersion: v1
kind: Service
metadata:
  name: url-shortener-service
  namespace: url-shortener
spec:
  selector:
    app: url-shortener
  type: NodePort
  ports:
    - port: 80
      targetPort: 8081
      nodePort: 30181
      protocol: TCP